### ISSUE TITLE
Error when using parseObject

### ISSUE THREAD

**Issue by pronebird** [teambition/jsonrpc-lite#11]
A very basic example:

```ts
const rawObjectToParse = { ... };
const { payload } = jsonrpc.parseObject(rawObjectToParse);

if (payload.method === 'some-method') {
 // ...
}
```

Emits:
```
Property 'method' does not exist on type 'NotificationObject | SuccessObject | RequestObject | ErrorObject | JsonRpcError'
```

Any solution to this?

**Comment by andersbc** [comment]
I have a very similar problem. I assume @pronebird uses typescript like me. 

See this question I posed on stackoverflow:
https://stackoverflow.com/questions/55671228/how-to-use-a-type-guard-when-the-type-is-declared-in-an-imported-module-jsonrpc. 

The [accepted answer](https://stackoverflow.com/a/55674014/) by [m93a](https://stackoverflow.com/users/1137334/m93a) suggests a workaround. 

However, it also states that:
> First of all, the best solution would be to convince the developers of the package to export all the important types. Because any updates to the package may cause the other solutions to stop working.

So the actual problem seems to be with what types are exported from [jsonrpc.d.ts](https://github.com/teambition/jsonrpc-lite/blob/master/jsonrpc.d.ts). 

I'm new to typescript, so I don't understand the details of the problem, and won't attempt a PR myself. This this is just what I gather so far.

**Comment by m93a** [comment]
The problem is that `parseObject` may produce many different kinds of objects (`SuccessObject`, `NotificationObject`, `RequestObject`, `ErrorObject`, `jsonrpc.JsonRpcError`) and there's little way to differentiate between them. The library should either provide type guards for them, or at least export all types that are relevant for the user, ideally both.
